### ISSUE TITLE
No new build for G4

### ISSUE THREAD

**Issue by Bleuzen** [TeamWin/android_device_lge_g4#2]
Hi the latest TWRP version for the G4 is still 3.2.0, but 3.2.1 got released.
The latest build failed: https://jenkins.twrp.me/job/g4-prod/4/

**Comment by mdPlusPlus** [comment]
According to the [xda thread](https://forum.xda-developers.com/g4/development/recovery-twrp-3-touch-recovery-t3442424) on the [TWRP site](https://twrp.me/lg/lgg4.html) you can get preview builds [here](http://droid.binbash.it:8008/TWRP/)

**Comment by Bleuzen** [comment]
@mdPlusPlus Yeah, found it already. Anyway thanks :D
